[package]
name = "etsi014-client"
version = "0.1.0"
edition = "2021"
description = "ETSI GS QKD 014 client library"
readme = "../README.md"
repository = "https://github.com/TUe-QTS/ETSI-QKD014-client"
keywords = ["etsi", "qkd"]
categories = ["api-bindings", "cryptography"]
license = "MIT"
rust-version = "1.74.1"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc"] }
libc = "0.2.158"
reqwest = { version = "0.12.7", features = ["native-tls"] }
secrets = "1.2.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tokio = "1.39.3"
url = "2.5.2"

[build-dependencies]
cbindgen = "0.27.0"
